<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;

class AssessmentOfi extends Model
{
    protected $fillable = [
        'assessment_id',
        'gamo_objective_id',
        'title',
        'description',
        'type',
        'priority',
        'status',
        'category',
        'recommended_action',
        'target_date',
        'current_level',
        'target_level',
        'gap_score',
        'created_by',
        'updated_by',
    ];

    protected $casts = [
        'target_date' => 'date',
        'gap_score' => 'decimal:2',
    ];

    /**
     * Get the assessment that owns the OFI
     */
    public function assessment(): BelongsTo
    {
        return $this->belongsTo(Assessment::class);
    }

    /**
     * Get the GAMO objective that owns the OFI
     */
    public function gamoObjective(): BelongsTo
    {
        return $this->belongsTo(GamoObjective::class);
    }

    /**
     * Get the user who created the OFI
     */
    public function creator(): BelongsTo
    {
        return $this->belongsTo(User::class, 'created_by');
    }

    /**
     * Get the user who last updated the OFI
     */
    public function updater(): BelongsTo
    {
        return $this->belongsTo(User::class, 'updated_by');
    }

    /**
     * Scope for auto-generated OFIs
     */
    public function scopeAutoGenerated($query)
    {
        return $query->where('type', 'auto');
    }

    /**
     * Scope for manual OFIs
     */
    public function scopeManual($query)
    {
        return $query->where('type', 'manual');
    }

    /**
     * Scope by status
     */
    public function scopeByStatus($query, string $status)
    {
        return $query->where('status', $status);
    }

    /**
     * Scope by priority
     */
    public function scopeByPriority($query, string $priority)
    {
        return $query->where('priority', $priority);
    }
}
